import 'package:flutter_test/flutter_test.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:kerfplan/domain/units/display_unit.dart';
import 'package:kerfplan/presentation/results/bar_diagram_geometry.dart';
import 'package:kerfplan/services/export/cut_report_text.dart';

import '../domain/optimizer/optimizer_test_support.dart';
import '../support/report_fixture.dart';

void main() async {
  await initializeDateFormatting('en');
  test('Fixed report contains real lengths, waste and disclaimer', () {
    final report = reportFor(
      fixed([stock(1000, quantity: 8)], [part(400, quantity: 2)]),
    );
    final text = cutReportText(report);
    for (final expected in [
      '1000 mm',
      '1. 400 mm',
      '2. 400 mm',
      '197 mm',
      '20.0%',
      '1 stock piece used',
      'Generated by KerfPlan',
      'Verify each measurement on the stock before cutting',
    ]) {
      expect(text, contains(expected));
    }
    expect(text, isNot(contains('8 stock pieces used')));
    expect(text, isNot(contains('private-project-id')));
    expect(report.purchaseLine, isNull);
    expect(text, isNot(contains('Purchase')));
  });

  test('two ordered cuts have only their actual between-parts kerf', () {
    final report = reportFor(fixed([stock(1000)], [part(400, quantity: 2)]));
    expect(report.bars.single.parts, ['1. 400 mm', '2. 400 mm']);
    expect(report.bars.single.kerfLine, 'Kerf loss: 3 mm');
    expect(report.bars.single.source.placedParts.last.kerfAfter.ticks, 0);
    expect(
      BarDiagramGeometry(report.bars.single.source).segments
          .where((s) => s.kind == BarSegmentKind.kerf),
      hasLength(1),
    );
    expect(cutReportText(report), isNot(contains('3. 400')));
  });

  test('Buy includes purchase quantity and concise clipboard line', () {
    final report = reportFor(buy(6000, [part(1800, quantity: 10)]));
    expect(report.purchaseLine, '6000 mm \u00d7 4');
    expect(cutReportText(report), contains('Purchase\n6000 mm \u00d7 4'));
    expect(cutReportText(report), contains('4 stock pieces to buy'));
  });

  test('partial jobs preserve both unplaced source identities and reasons', () {
    final report = reportFor(
      fixed(
        [stock(1000)],
        [
          part(6500, quantity: 2, id: 'top', name: 'Frame top'),
          part(6500, id: 'side', name: 'Frame side'),
          part(400, quantity: 3, id: 'brace', name: 'Brace'),
        ],
      ),
    );
    final text = cutReportText(report);
    expect(text, contains('Placed 2 of 6 parts'));
    expect(text, contains('Unplaced parts (4)'));
    expect(text, contains('Frame top \u2014 6500 mm \u00d7 2'));
    expect(text, contains('Frame side \u2014 6500 mm \u00d7 1'));
    expect(
      text,
      contains('This part is longer than the largest usable stock length.'),
    );
    expect(text, contains('Not enough stock remains to place this part.'));
    expect(
      report.unplaced.map((item) => item.source.sourcePartId),
      report.result.unplaced.map((item) => item.sourcePartId).toSet().toList(),
    );
    expect(report.bars, hasLength(1));
  });

  test('imperial output and purchase line use fractions', () {
    final report = reportFor(
      buy(2439, [part(1200, quantity: 2)]),
      unit: DisplayUnit.ftIn,
    );
    expect(report.purchaseLine, contains("8' 0\""));
    expect(cutReportText(report), contains("3' 11-1/4\""));
    expect(cutReportText(report), isNot(contains('47.244')));
  });

  test('optional metadata is omitted cleanly', () {
    final text = cutReportText(reportFor(fixed([stock(1000)], [part(400)])));
    expect(text, isNot(contains('null')));
    expect(text, isNot(contains('Material:')));
  });

  test('material and note remain readable user content', () {
    final text = cutReportText(
      reportFor(
        fixed([stock(1000)], [part(400)]),
        material: '40x20 Steel',
        note: 'South wall',
      ),
    );
    expect(text, contains('Garage Frame\n40x20 Steel\nSouth wall'));
  });

  test(
    'snapshot preserves bars, placed order, exact totals and supplied time',
    () {
      final report = reportFor(
        fixed(
          [stock(6000), stock(3000, id: 'short', quantity: 2)],
          [part(5500, id: 'tall'), part(2500, quantity: 2)],
        ),
      );
      expect(
        report.bars.map((bar) => bar.source),
        orderedEquals(report.result.bars),
      );
      for (final bar in report.bars) {
        expect(bar.parts.length, bar.source.placedParts.length);
        for (var i = 0; i < bar.parts.length; i++) {
          expect(
            bar.parts[i],
            startsWith('${bar.source.placedParts[i].orderIndex + 1}.'),
          );
        }
      }
      expect(
        report.summary.firstWhere((m) => m.label == 'Total waste').value,
        '1500 mm',
      );
      expect(
        report.summary.firstWhere((m) => m.label == 'Reusable leftovers').value,
        '1500 mm',
      );
      expect(
        report.summary.firstWhere((m) => m.label == 'Scrap').value,
        '0 mm',
      );
      expect(report.result.totalWaste.ticks, 15000000);
      expect(report.generatedAt, reportDate);
      expect(report.generatedDate, 'Sep 26, 2026');
      expect(() => report.bars.clear(), throwsUnsupportedError);
      expect(() => report.bars.first.parts.clear(), throwsUnsupportedError);
    },
  );

  test('zero tail is not labeled as a reusable offcut', () {
    final report = reportFor(fixed([stock(1000)], [part(1000)], reusable: 0));
    expect(report.bars.single.tailLine, 'Leftover: 0 mm');
  });

  test('all-unplaced report is complete without any bar cards', () {
    final report = reportFor(fixed([stock(1000)], [part(1200, quantity: 3)]));
    expect(report.bars, isEmpty);
    expect(cutReportText(report), contains('0 stock pieces used'));
    expect(cutReportText(report), contains('Placed 0 of 3 parts'));
    expect(cutReportText(report), contains('Unplaced parts (3)'));
  });
}
